version: "1"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: groupDb
    hostname: groupDb
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Welkom12345"
      ACCEPT_EULA: "Y"
      ConnectionStrings__DefaultConnection: "Server=localhost,1433;User=SA;Password=Welkom12345;TrustServerCertificate=true"