// <auto-generated />
using System;
using GroupingService.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupingService.DataAccessLayer.Migrations
{
    [DbContext(typeof(GroupDbContext))]
    [Migration("20230328110603_RoomCodeAsPK")]
    partial class RoomCodeAsPK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GroupingService.DataAccessLayer.Models.Group", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomCode");

                    b.ToTable("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
