/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/assets/redbutton/scene.gltf -t -r public
Author: Wolf (https://sketchfab.com/wolfmic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-button-e7685cccf7364682bc6a7883d0b8c503
Title: Red Button
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export function Redbutton(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/redbutton/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={10}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.23}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/redbutton/scene.gltf')
