# This is a basic workflow to help you get started with Actions

name: .NET Core 6 CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, shared-library-remove ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PATH_TO_SLN: './LOUPE_Backend/LOUPE_Backend.sln'
  DOCKER_IMAGE_NAME: loupe_image:latest
  DOCKER_REPO_NAME: 418262/loupe_back-end


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0' ]
    
    steps:
      - uses: actions/checkout@v2
      #- name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      #  uses: actions/setup-dotnet@v1.7.2
       # with:
       #   dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore $PATH_TO_SLN
      - name: Build
        run: dotnet build --configuration Release --no-restore $PATH_TO_SLN
    
  test:
    needs:
    - build
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0' ]
        
    steps:
      - uses: actions/checkout@v2
      #- name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
       # uses: actions/setup-dotnet@v1.7.2
       # with:
        #  dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore $PATH_TO_SLN
      - name: Test
        run: dotnet test --no-restore $PATH_TO_SLN #--verbosity normal